### ISSUE TITLE
Semantic breaks: a suggestion

### ISSUE THREAD

**Issue by rjmk** [FilWisher/exceptions-in-haskell#1]
> Hints for Preparing Documents
> 
> Most documents go through several versions (always more than you expected) before they are finally finished. Accordingly, you should do whatever possible to make the job of changing them easy.
> 
> First, when you do the purely mechanical operations of typing, type so subsequent editing will be easy. Start each sentence on a new line. Make lines short, and break lines at natural places, such as after commas and semicolons, rather than randomly. Since most people change documents by rewriting phrases and adding, deleting and rearranging sentences, these precautions simplify any editing you have to do later.
> 
> — Brian W. Kernighan, 1974

1: http://rhodesmill.org/brandon/2012/one-sentence-per-line/
2: https://scott.mn/2014/02/21/semantic_linewrapping/

**Comment by FilWisher** [comment]
This is amazing, it has changed my life.
